/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as authLayoutRouteImport } from './pages/(auth)/layout'
import { Route as authIndexRouteImport } from './pages/(auth)/index'
import { Route as PartyGameIdRouteImport } from './pages/party/$gameId'
import { Route as ManagerConfigRouteImport } from './pages/manager/config'
import { Route as ManagerQuizLayoutRouteImport } from './pages/manager/quiz/layout'
import { Route as ManagerQuizIndexRouteImport } from './pages/manager/quiz/index'
import { Route as authManagerIndexRouteImport } from './pages/(auth)/manager/index'
import { Route as PartyManagerGameIdRouteImport } from './pages/party/manager/$gameId'
import { Route as ManagerQuizQuizIdRouteImport } from './pages/manager/quiz/$quizId'

const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyGameIdRoute = PartyGameIdRouteImport.update({
  id: '/party/$gameId',
  path: '/party/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerConfigRoute = ManagerConfigRouteImport.update({
  id: '/manager/config',
  path: '/manager/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizLayoutRoute = ManagerQuizLayoutRouteImport.update({
  id: '/manager/quiz',
  path: '/manager/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizIndexRoute = ManagerQuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerQuizLayoutRoute,
} as any)
const authManagerIndexRoute = authManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyManagerGameIdRoute = PartyManagerGameIdRouteImport.update({
  id: '/party/manager/$gameId',
  path: '/party/manager/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizQuizIdRoute = ManagerQuizQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => ManagerQuizLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/manager/quiz': typeof ManagerQuizLayoutRouteWithChildren
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/manager/quiz/$quizId': typeof ManagerQuizQuizIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/manager/': typeof authManagerIndexRoute
  '/manager/quiz/': typeof ManagerQuizIndexRoute
}
export interface FileRoutesByTo {
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/manager/quiz/$quizId': typeof ManagerQuizQuizIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/manager': typeof authManagerIndexRoute
  '/manager/quiz': typeof ManagerQuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/manager/quiz': typeof ManagerQuizLayoutRouteWithChildren
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/(auth)/': typeof authIndexRoute
  '/manager/quiz/$quizId': typeof ManagerQuizQuizIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/(auth)/manager/': typeof authManagerIndexRoute
  '/manager/quiz/': typeof ManagerQuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/manager/quiz'
    | '/manager/config'
    | '/party/$gameId'
    | '/'
    | '/manager/quiz/$quizId'
    | '/party/manager/$gameId'
    | '/manager/'
    | '/manager/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/manager/config'
    | '/party/$gameId'
    | '/'
    | '/manager/quiz/$quizId'
    | '/party/manager/$gameId'
    | '/manager'
    | '/manager/quiz'
  id:
    | '__root__'
    | '/(auth)'
    | '/manager/quiz'
    | '/manager/config'
    | '/party/$gameId'
    | '/(auth)/'
    | '/manager/quiz/$quizId'
    | '/party/manager/$gameId'
    | '/(auth)/manager/'
    | '/manager/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  ManagerQuizLayoutRoute: typeof ManagerQuizLayoutRouteWithChildren
  ManagerConfigRoute: typeof ManagerConfigRoute
  PartyGameIdRoute: typeof PartyGameIdRoute
  PartyManagerGameIdRoute: typeof PartyManagerGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/$gameId': {
      id: '/party/$gameId'
      path: '/party/$gameId'
      fullPath: '/party/$gameId'
      preLoaderRoute: typeof PartyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/config': {
      id: '/manager/config'
      path: '/manager/config'
      fullPath: '/manager/config'
      preLoaderRoute: typeof ManagerConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quiz': {
      id: '/manager/quiz'
      path: '/manager/quiz'
      fullPath: '/manager/quiz'
      preLoaderRoute: typeof ManagerQuizLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quiz/': {
      id: '/manager/quiz/'
      path: '/'
      fullPath: '/manager/quiz/'
      preLoaderRoute: typeof ManagerQuizIndexRouteImport
      parentRoute: typeof ManagerQuizLayoutRoute
    }
    '/(auth)/manager/': {
      id: '/(auth)/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof authManagerIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/manager/$gameId': {
      id: '/party/manager/$gameId'
      path: '/party/manager/$gameId'
      fullPath: '/party/manager/$gameId'
      preLoaderRoute: typeof PartyManagerGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quiz/$quizId': {
      id: '/manager/quiz/$quizId'
      path: '/$quizId'
      fullPath: '/manager/quiz/$quizId'
      preLoaderRoute: typeof ManagerQuizQuizIdRouteImport
      parentRoute: typeof ManagerQuizLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authIndexRoute: typeof authIndexRoute
  authManagerIndexRoute: typeof authManagerIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authIndexRoute: authIndexRoute,
  authManagerIndexRoute: authManagerIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface ManagerQuizLayoutRouteChildren {
  ManagerQuizQuizIdRoute: typeof ManagerQuizQuizIdRoute
  ManagerQuizIndexRoute: typeof ManagerQuizIndexRoute
}

const ManagerQuizLayoutRouteChildren: ManagerQuizLayoutRouteChildren = {
  ManagerQuizQuizIdRoute: ManagerQuizQuizIdRoute,
  ManagerQuizIndexRoute: ManagerQuizIndexRoute,
}

const ManagerQuizLayoutRouteWithChildren =
  ManagerQuizLayoutRoute._addFileChildren(ManagerQuizLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  ManagerQuizLayoutRoute: ManagerQuizLayoutRouteWithChildren,
  ManagerConfigRoute: ManagerConfigRoute,
  PartyGameIdRoute: PartyGameIdRoute,
  PartyManagerGameIdRoute: PartyManagerGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
