/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as authLayoutRouteImport } from './pages/(auth)/layout'
import { Route as HostIndexRouteImport } from './pages/host/index'
import { Route as authIndexRouteImport } from './pages/(auth)/index'
import { Route as PartyGameIdRouteImport } from './pages/party/$gameId'
import { Route as HostCreateRouteImport } from './pages/host/create'
import { Route as HostConfigRouteImport } from './pages/host/config'
import { Route as HostQuizLayoutRouteImport } from './pages/host/quiz/layout'
import { Route as HostQuizIndexRouteImport } from './pages/host/quiz/index'
import { Route as PartyManagerGameIdRouteImport } from './pages/party/manager/$gameId'
import { Route as HostQuizQuizIdRouteImport } from './pages/host/quiz/$quizId'
import { Route as authHostLoginRouteImport } from './pages/(auth)/host/login'

const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyGameIdRoute = PartyGameIdRouteImport.update({
  id: '/party/$gameId',
  path: '/party/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostCreateRoute = HostCreateRouteImport.update({
  id: '/host/create',
  path: '/host/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HostConfigRoute = HostConfigRouteImport.update({
  id: '/host/config',
  path: '/host/config',
  getParentRoute: () => rootRouteImport,
} as any)
const HostQuizLayoutRoute = HostQuizLayoutRouteImport.update({
  id: '/host/quiz',
  path: '/host/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const HostQuizIndexRoute = HostQuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostQuizLayoutRoute,
} as any)
const PartyManagerGameIdRoute = PartyManagerGameIdRouteImport.update({
  id: '/party/manager/$gameId',
  path: '/party/manager/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostQuizQuizIdRoute = HostQuizQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => HostQuizLayoutRoute,
} as any)
const authHostLoginRoute = authHostLoginRouteImport.update({
  id: '/host/login',
  path: '/host/login',
  getParentRoute: () => authLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/host/quiz': typeof HostQuizLayoutRouteWithChildren
  '/host/config': typeof HostConfigRoute
  '/host/create': typeof HostCreateRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/host/': typeof HostIndexRoute
  '/host/login': typeof authHostLoginRoute
  '/host/quiz/$quizId': typeof HostQuizQuizIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/host/quiz/': typeof HostQuizIndexRoute
}
export interface FileRoutesByTo {
  '/host/config': typeof HostConfigRoute
  '/host/create': typeof HostCreateRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/host': typeof HostIndexRoute
  '/host/login': typeof authHostLoginRoute
  '/host/quiz/$quizId': typeof HostQuizQuizIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/host/quiz': typeof HostQuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/host/quiz': typeof HostQuizLayoutRouteWithChildren
  '/host/config': typeof HostConfigRoute
  '/host/create': typeof HostCreateRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/(auth)/': typeof authIndexRoute
  '/host/': typeof HostIndexRoute
  '/(auth)/host/login': typeof authHostLoginRoute
  '/host/quiz/$quizId': typeof HostQuizQuizIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/host/quiz/': typeof HostQuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/host/quiz'
    | '/host/config'
    | '/host/create'
    | '/party/$gameId'
    | '/'
    | '/host/'
    | '/host/login'
    | '/host/quiz/$quizId'
    | '/party/manager/$gameId'
    | '/host/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/host/config'
    | '/host/create'
    | '/party/$gameId'
    | '/'
    | '/host'
    | '/host/login'
    | '/host/quiz/$quizId'
    | '/party/manager/$gameId'
    | '/host/quiz'
  id:
    | '__root__'
    | '/(auth)'
    | '/host/quiz'
    | '/host/config'
    | '/host/create'
    | '/party/$gameId'
    | '/(auth)/'
    | '/host/'
    | '/(auth)/host/login'
    | '/host/quiz/$quizId'
    | '/party/manager/$gameId'
    | '/host/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  HostQuizLayoutRoute: typeof HostQuizLayoutRouteWithChildren
  HostConfigRoute: typeof HostConfigRoute
  HostCreateRoute: typeof HostCreateRoute
  PartyGameIdRoute: typeof PartyGameIdRoute
  HostIndexRoute: typeof HostIndexRoute
  PartyManagerGameIdRoute: typeof PartyManagerGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/$gameId': {
      id: '/party/$gameId'
      path: '/party/$gameId'
      fullPath: '/party/$gameId'
      preLoaderRoute: typeof PartyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/create': {
      id: '/host/create'
      path: '/host/create'
      fullPath: '/host/create'
      preLoaderRoute: typeof HostCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/config': {
      id: '/host/config'
      path: '/host/config'
      fullPath: '/host/config'
      preLoaderRoute: typeof HostConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/quiz': {
      id: '/host/quiz'
      path: '/host/quiz'
      fullPath: '/host/quiz'
      preLoaderRoute: typeof HostQuizLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/quiz/': {
      id: '/host/quiz/'
      path: '/'
      fullPath: '/host/quiz/'
      preLoaderRoute: typeof HostQuizIndexRouteImport
      parentRoute: typeof HostQuizLayoutRoute
    }
    '/party/manager/$gameId': {
      id: '/party/manager/$gameId'
      path: '/party/manager/$gameId'
      fullPath: '/party/manager/$gameId'
      preLoaderRoute: typeof PartyManagerGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/quiz/$quizId': {
      id: '/host/quiz/$quizId'
      path: '/$quizId'
      fullPath: '/host/quiz/$quizId'
      preLoaderRoute: typeof HostQuizQuizIdRouteImport
      parentRoute: typeof HostQuizLayoutRoute
    }
    '/(auth)/host/login': {
      id: '/(auth)/host/login'
      path: '/host/login'
      fullPath: '/host/login'
      preLoaderRoute: typeof authHostLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authIndexRoute: typeof authIndexRoute
  authHostLoginRoute: typeof authHostLoginRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authIndexRoute: authIndexRoute,
  authHostLoginRoute: authHostLoginRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface HostQuizLayoutRouteChildren {
  HostQuizQuizIdRoute: typeof HostQuizQuizIdRoute
  HostQuizIndexRoute: typeof HostQuizIndexRoute
}

const HostQuizLayoutRouteChildren: HostQuizLayoutRouteChildren = {
  HostQuizQuizIdRoute: HostQuizQuizIdRoute,
  HostQuizIndexRoute: HostQuizIndexRoute,
}

const HostQuizLayoutRouteWithChildren = HostQuizLayoutRoute._addFileChildren(
  HostQuizLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  HostQuizLayoutRoute: HostQuizLayoutRouteWithChildren,
  HostConfigRoute: HostConfigRoute,
  HostCreateRoute: HostCreateRoute,
  PartyGameIdRoute: PartyGameIdRoute,
  HostIndexRoute: HostIndexRoute,
  PartyManagerGameIdRoute: PartyManagerGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
